### ISSUE TITLE
issue when activating latest version

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#27]
i get this error when trying to activate the latest version of topologic sverchok:

Traceback (most recent call last):
  File "/usr/share/blender/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.2/scripts/addons/TopologicSverchok-main/__init__.py", line 383, in <module>
    imported_modules = make_node_list()
  File "/home/sinasta/.config/blender/3.2/scripts/addons/TopologicSverchok-main/__init__.py", line 378, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'topologicsverchok.nodes.Topologic.IFCExportToHBJSON'

**Comment by Sinasta** [comment]
This gets fixed by renaming:
nodes/Topologic/IFCExportToHBSJON.py
to:
nodes/Topologic/IFCExportToHBJSON.py

**Comment by Sinasta** [comment]
And line 259 in __init__.py should be changed from:
("Topologic.TopologyByImportedIFC", "SvTopologyByImportedIFC",]
to:
("Topologic.TopologyByImportedIFC", "SvTopologyByImportedIFC")]
i think. Thank you for your work Wassim.

**Comment by wassimj** [comment]
Yes sorry! fixing it now!

**Comment by Sinasta** [comment]
Thank you very much! There is another issue, maybe it is just me, but i don't see the new node: IFC.ExportToHBJSON

**Comment by wassimj** [comment]
Can you check this? https://github.com/wassimj/TopologicSverchok/blob/v0.8.0.1/nodes/Topologic/IFCExportToHBSJON.py

**Comment by wassimj** [comment]
I have updated github and the binary release for Windows. Can you please check again? Much appreciated.

**Comment by Sinasta** [comment]
I still can't see the new node sadly:
![Screenshot from 2022-04-08 17-03-06](https://user-images.githubusercontent.com/64699866/162469452-ef7c29c4-ad66-4729-9b88-bcb081437322.png)

**Comment by wassimj** [comment]
Really sorry! Thanks for catching it. It should all be fixed now. (I hope!)

**Comment by Sinasta** [comment]
Thank you for your work. I installed the addon with your latest changes but i still can't find the IFCExportToHBJSON node.
![Screenshot from 2022-04-09 16-38-45](https://user-images.githubusercontent.com/64699866/162578931-a45aa239-d4e2-4320-b81d-99926913d44e.png)

**Comment by wassimj** [comment]
I am suspecting it is not displaying it for you because you do not have honeybee installed. Please check the error outputs. There is probably a warning about that.

**Comment by Sinasta** [comment]
i don't have any error when starting blender and i have honeybee and ladybug installed.
I am able to run the import part of IFCExportToHBJSON.py in Blender without problems (see screenshot).
![Screenshot from 2022-04-09 18-22-10](https://user-images.githubusercontent.com/64699866/162582614-40e222d2-09b5-42da-976d-0bc2c841115a.png)

**Comment by wassimj** [comment]
Do you also have openstudio installed? Do you see the EnergyModel nodes?

**Comment by Sinasta** [comment]
yes i have openstudio 3.3.0 installed and i do see the EnergyModel nodes.
![Screenshot from 2022-04-09 19-12-40](https://user-images.githubusercontent.com/64699866/162584383-b72bc286-b803-4eb1-9a68-3cbff61dfc0f.png)

**Comment by wassimj** [comment]
Then please check if the name is correct in two locations inside __init__.py and if the file is in the nodes/Topologic folder

**Comment by Sinasta** [comment]
The name is indeed correct in both locations in the init.py and the file does exist in the topologic folder.
Another thing i just realised is that i am missing the HBJSONByTopology node.

**Comment by Sinasta** [comment]
now i added this line: ("Topologic.HBJSONByTopology", "SvHBJSONByTopology"),
at line 267 in the init.py and now the EnergyModel.HBJSONByTopology just appeared in the nodetree.
I don't know if both problems are related.

**Comment by wassimj** [comment]
Sorry not at my computer now. Will investigate

**Comment by Sinasta** [comment]
I think i fixed the problem by replacing: SvHBJSONByIFC with SvIFCExportToHBJSON in the IFCExportToHBJSON.py file

**Comment by wassimj** [comment]
That explains it! A case of copy paste error. I will fix soon

**Comment by Sinasta** [comment]
Oh and i was missing the Neo4jGraphNodeLabels node. Which git fixed by replacing: SvNeo4jGraphNodelLabels with SvNeo4jGraphNodeLabels in the init.py. It seems to me that this is a typo aswell. I will continue to check a bit if i am missing other nodes and than report.

**Comment by Sinasta** [comment]
replacing SvSpeckleRecieve with SvSpeckleReceive in the init.py makes the Speckle.Receive node appear.

**Comment by wassimj** [comment]
That is surprising. I know these are nodes that I recently used.

**Comment by Sinasta** [comment]
adding the line:  ("Topologic.EnergyModelExportToHBJSON", "SvEnergyModelExportToHBJSON"),
to the init.py on line 271 makes the node: EnergyModel.ExportToHBJSON appear

**Comment by Sinasta** [comment]
I checked everything and the rest seems to be fine. There are some seemingly depracted nodes that are still called in the init.py: 

SvEdgeSharedVertices
SvFaceTriangulate
SvTopologyContexts

I guess those could be deleted but doesnt matter apparently.

SvEnergyModelByImportedIFC seems to be drawn twice, once in Openstudio submenu and once in IFC submenu (it seems that it fits more in the Openstudio submenu and could be deleted from the IFC submenu)

**Comment by wassimj** [comment]
Thank you. That was be design 🙂

**Comment by wassimj** [comment]
All the above issues should've been fixed in the following release. Kindly verify and let me know if you continue to find issues with it. Thank you for your efforts in finding these problems.
https://github.com/wassimj/TopologicSverchok/releases/tag/v0.8.0.2

**Comment by Sinasta** [comment]
Thank's for the effort i really appreciate your work on topologic. With your latest changes there is still the EnergyModel.HBJSONByTopology node missing. which gets fixed with this:

> now i added this line: ("Topologic.HBJSONByTopology", "SvHBJSONByTopology"),
> at line 267 in the init.py and now the EnergyModel.HBJSONByTopology just appeared in the nodetree.
> I don't know if both problems are related.

Furthermore the Neo4jGraph.NodeLabels is missing in the nodetree. That gets fixed by:

> Oh and i was missing the Neo4jGraphNodeLabels node. Which git fixed by replacing: SvNeo4jGraphNodelLabels with SvNeo4jGraphNodeLabels in the init.py. It seems to me that this is a typo aswell. I will continue to check a bit if i am missing other nodes and than report.

The rest seems to be fixed now :)

**Comment by wassimj** [comment]
Thank you. HBJSON.ByTopology is deprecated and should not be added to init. Instead, use EnergyModelExportToHBJSON
I will fix the mis-spelled SvNeo4jGraphNodeLabels in the init file. Thank you for your eagle eyes.

**Comment by Sinasta** [comment]
Oh that is good to know :)
BTW i would appreciate a lot if you could somehow spare some time to give some explanations on how to use all the honeybee/openstudio functionalities (i know that there is your video on youtube but you added plenty of new functions and i would appreciate an update on the usage). Basically what i would like to achieve is to 'evaluate' somehow the energy performance (and potentially lightning performance with radiance aswell as airflow with openfoam somehow similar to the ladybug suite in grasshopper) of a cell complex with apertures (doors, window, shading surfaces). I don't know if this is already possible or if the vi-suite addon should be used for that purpose for now. Thanks anyways for your awesome work :)

**Comment by wassimj** [comment]
energy performance is possible, but not lighting and airflow at this moment. I need the help of experts in these areas to see what is needed. I know the are ladybug nodes in sverchok that can be useful? When I have some free time, I will do a workshop on energy analysis.

**Comment by Sinasta** [comment]
perfect i would love to see a small workshop on energy performance. For what concerns ladybug and openfoam integration i have the feeling that [Ryan Southall](https://github.com/rgsouthall) with his Blender addon [Vi-suite](https://github.com/rgsouthall/vi-suite07) could be of good help to integrate Radiance, energy+ and openfoam in topologic sverchok.
