### ISSUE TITLE
linux version: libTopologicCore.so.0 file too short + other problems

### ISSUE THREAD

**Issue by sanzoghenzo** [wassimj/TopologicSverchok#32]
Hi,
I just downloaded the latest release, but when I try to enable it in blender it throws this error:

```
Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sanzo/.config/blender/3.1/scripts/addons/topologicsverchok/__init__.py", line 56, in <module>
    import topologic
ImportError: /home/sanzo/.config/blender/3.1/scripts/addons/topologicsverchok/site-packages/topologic-linux/./libTopologicCore.so.0: file too short
```

the file is 25 bytes  in size and contains the "libTopologicCore.so.0.0.0" text.

Obviously this should be a link, and indeed replacing it to a symlink to `libTopologicCore.so.0.0.0` solves this error, but another one appears:

```
Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sanzo/.config/blender/3.1/scripts/addons/topologicsverchok/__init__.py", line 56, in <module>
    import topologic
ImportError: libTKernel.so.7: cannot open shared object file: No such file or directory
```

I don't know much about C++ compliation, but it seems there's something broken in the build toolchain.

Also, why there are both `topologic` and `topologic-linux` packages in the `site-packages` folder? they seem to be identical in size and file contents.

**Comment by wassimj** [comment]
Thank you for flagging this. I will look at the build tool chain soon and fix it

**Comment by wassimj** [comment]
@sanzoghenzo I have updated the linux release. Please test and let me know if this is now resolved. Thank you for spotting it.

**Comment by sanzoghenzo** [comment]
Hi, thanks for the quick update!

Unfortunately, it still doesn't work for me, but I realized it's not your fault.
the files at the left are from your zip file, those at the right are in the blender addon folder. 

![image](https://user-images.githubusercontent.com/977953/170926348-deb1c6c0-61c8-4b38-adeb-56c557167e8e.png)

I suppose blender's add-on installer doesn't like symlinks...

after fixing the symlinks it still complains about missing `libTKernel.so.7`, and indeed there's no such file:

![image](https://user-images.githubusercontent.com/977953/170927091-03f074e0-7406-4f49-b64a-dea39057ad14.png)

**Comment by wassimj** [comment]
Oh that is disappointing. OK, I have removed all the symlinks and uploaded a new -B release in the same place. It works perfectly well on my Ubuntu Groovy Gorilla Linux. So, not sure what the problem is. There shouldn't be a libTKernel.so.7  It should either be 7.7 or 7.7.0. In any case, I removed all the .7.7 and .7.7.0 files and left only .so files and it seems to be working fine. Thank you for your patience. I hope it works, but if not, please reply here and I will try to debug some more.

**Comment by wassimj** [comment]
Found out I still had a glitch finding the libTopologicCore.so.0 file. I fixed that (hopefully) with the patchelf command. I uploaded a "-C" version to the release. Hopefully that solves it. Please let me know.

**Comment by sanzoghenzo** [comment]
Just tried the "-D" version, the libTopologicCore problem is gone, but unfortunately I still have the libTKernel.so.7 problem.
Not only that, I tried to make a symlink of that file and repeat for every file it told me... here's the list:

```sh
ln -s libTKernel.so libTKernel.so.7
ln -s libTKMath.so libTKMath.so.7
ln -s libTKOffset.so libTKOffset.so.7
ln -s libTKPrim.so libTKPrim.so.7
ln -s libTKMesh.so libTKMesh.so.7
ln -s libTKBO.so libTKBO.so.7
ln -s libTKShHealing.so libTKShHealing.so.7
ln -s libTKG3d.so libTKG3d.so.7
ln -s libTKG2d.so libTKG2d.so.7
ln -s libTKGeomBase.so libTKGeomBase.so.7
ln -s libTKGeomAlgo.so libTKGeomAlgo.so.7
ln -s libTKTopAlgo.so libTKTopAlgo.so.7
ln -s libTKFillet.so libTKFillet.so.7.7
ln -s libTKBool.so libTKBool.so.7.7
ln -s libTKBRep.so libTKBRep.so.7.7
```
At this point I got another error:

```
Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sanzo/.config/blender/3.1/scripts/addons/topologicsverchok/__init__.py", line 56, in <module>
    import topologic
ImportError: /home/sanzo/.config/blender/3.1/scripts/addons/topologicsverchok/site-packages/topologic/./libTopologicCore.so.0: undefined symbol: _ZN24BRepBuilderAPI_MakeShape5BuildEv
```

I have no idea of what's going on here!

**Comment by wassimj** [comment]
This beyond my ability. All I can suggest is to see if you have a conflicting installation of OCCT. Perhaps from FreeCAD or another topologic installation as a pure python module? On my Linux installation I have nothing OCCT related in /usr/local/lib and it works.

**Comment by Sinasta** [comment]
I had a similar issue and it was caused by the interaction with another Blender addon called Vi-suite which hat netgen and by this some opencascade libraries bundled. I would try deactivating all Blender Addons and cleaning all opencascade installs in the python directory

**Comment by arunkvijay** [comment]
`Traceback (most recent call last):
  File "/home/arun/Apps/blender-3.2.1-linux-x64/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/arun/.config/blender/3.2/scripts/addons/topologicsverchok/__init__.py", line 56, in <module>
    import topologic
ImportError: /home/arun/.config/blender/3.2/scripts/addons/topologicsverchok/site-packages/topologic/./libTopologicCore.so.0: file too short`

I have the same issue with the latest version [v.0.8.1.10]. I have removed Freecad installation

**Comment by wassimj** [comment]
I have updated the release. Can you please delete your version and re-download and let me know? Thanks

**Comment by wassimj** [comment]
If it continues to give the same error, I think I know why. The following link seems wrong:
/home/arun/.config/blender/3.2/scripts/addons/topologicsverchok/site-packages/topologic/./libTopologicCore.so.0
There shouldn't be a /./ between topologic and libTopologicCore.so.0

**Comment by arunkvijay** [comment]
This is resolved now. Thank you
